### ISSUE TITLE
anvil-provision-server constraint will cause resource failures

### ISSUE THREAD

**Issue by fabbione** [ClusterLabs/anvil#312]
```
# anvil-provision-server --ci-test --name an-test-deploy1 --os centos-stream9 --cpu 4 --ram 4G --storage-group "Storage group 1" --storage-size 30G --install-media CentOS-Stream-9-latest-x86_64-dvd1.iso --driver-disc deploy1.iso
```

all good, vm is running on a01n01.

```
# anvil-provision-server --ci-test --name an-test-deploy2 --os centos-stream9 --cpu 4 --ram 4G --storage-group "Storage group 1" --storage-size 30G --install-media CentOS-Stream-9-latest-x86_64-dvd1.iso --driver-disc deploy2.iso
```

exposed a race condition, seen for the first time.

```
[root@an-a01n02 ~]# drbdadm status
an-test-deploy1 role:Secondary
  disk:UpToDate
  an-a01n01 role:Primary
    peer-disk:UpToDate

an-test-deploy2 role:Primary
  disk:UpToDate
  an-a01n01 role:Secondary
    peer-disk:UpToDate
```

drbd went primary on n02 first.

whatever adds the resource constraint on:

```
  Resource: an-test-deploy2
    Enabled on:
      Node: an-a01n02 (score:100) (id:location-an-test-deploy2-an-a01n02-100)
      Node: an-a01n01 (score:200) (id:location-an-test-deploy2-an-a01n01-200)
    Constraint: location-an-test-deploy2
      Rule: score=-INFINITY (id:location-an-test-deploy2-rule)
        Expression: drbd-fenced_an-test-deploy2 eq 1 (id:location-an-test-deploy2-rule-expr)
```

has basically been asking pcmk to move the resource to n01, causing:

```
  * an-test-deploy2     (ocf::alteeve:server):   FAILED an-a01n02 (blocked)

Failed Resource Actions:
  * an-test-deploy2_stop_0 on an-a01n02 'error' (1): call=64, status='Timed Out', exitreason='Resource agent did not complete within 5m', last-rc-change='Wed Mar 22 12:19:19 2023', queued=0ms, exec=300008ms
```

logs from n02 shows that 

```
2023/03/22 12:18:59:ocf:alteeve:server:1337; We've been asked to migrating the server: [an-test-deploy2] to: [an-a01n02].
2023/03/22 12:19:03:ocf:alteeve:server:1622; Asked to validate that the server: [an-test-deploy2] is able to run.
2023/03/22 12:19:04:ocf:alteeve:server:1829; The server wants to use: [/dev/drbd/by-res/an-test-deploy2/0] as a hard drive, which is backed by the logical volume: [/dev/anvil-test-vg/an-test-deploy2_0]. It is ready to use.
2023/03/22 12:19:04:DRBD.pm:209;
2023/03/22 12:19:04:Remote.pm:1042; Adding the target: [an-a01n01]:[22]'s RSA fingerprint to: [root]'s list of known hosts.
2023/03/22 12:19:19:Server.pm:1234; The migration was successfully completed in: [15 s].
2023/03/22 12:19:19:DRBD.pm:209;
2023/03/22 12:19:19:ocf:alteeve:server:1602; Success, exiting with '0'.
2023/03/22 12:19:20:ocf:alteeve:server:1074; We've been asked to stop the server: [an-test-deploy2].
2023/03/22 12:19:21:Server.pm:2145; The server: [an-test-deploy2] is already off.
[snip]
2023/03/22 12:20:52:ScanCore.pm:1786; [ Warning ] - We are "SyncSource" for at least one resource, meaning that a peer is copying data from our storage in order to synchronize. As such, all shut down options are disabled until the sync ends or the peer goes offline.
```

**Comment by digimer** [comment]
Tasks; 
1. When provisioning a server;
 - First, check if either node is SyncSource, if so use that node.
 - Second, check which node has the most servers by RAM count, use that node.
2. Provision;
 - Create DRBD resource, force primary on install target
 - Create pacemaker resource in stopped state
 - Set location constraint to prefer target node
 - Boot server

**Comment by digimer** [comment]
I'm unable to reproduce, but 83aa4e6, now in PR#319, adds checks to detect and recover resources in a FAILED state. This should resolve this issue, albeit obliquely. If you have a reliable reproducer, I'd still be very keen to try to find the root of the issue, as this is obviously a bandage solution.

**Comment by digimer** [comment]
Oh! I wonder if I don't check/wait to confirm that pacemaker is ready, I'll check that.

**Comment by fabbione** [comment]
we know this is not fixed yet as we don´t do atomic creation of the resource + constrains yet.

**Comment by digimer** [comment]
PR#335 should now add atomic creation.

**Comment by fabbione** [comment]
It appears to be fixed by PR#335, tho given it´s a race condition triggered only from time to time in CI, we will keep an eye over time.

**Comment by fabbione** [comment]
I haven´t been able to reproduce the problem in a while.
