### ISSUE TITLE
anvil-provion-server fails to schedule jobs.

### ISSUE THREAD

**Issue by fabbione** [ClusterLabs/anvil#323]
Fresh brand new deployment, the nodes have enough resources in RAM and disk to support at least 7 VMs.

[root@an-a01n01 ~]# for i in 1 2 3 4 5; do echo DEPLOY$i ; anvil-provision-server --ci-test --name an-test-deploy${i} --os centos-stream9 --cpu 4 --ram 4G --storage-group "Storage group 1" --storage-size 10G --install-media CentOS-Stream-9-latest-x86_64-dvd1.iso --driver-disc deploy${i}.iso; done

this will cause havoc, some VMs are started, others are not. When VMs are not started, there are no traces in the logs or on console.

Re-testing requires a full redeploy due to the anvil-delete-server bug.

**Comment by fabbione** [comment]
root problem is different.

**Comment by fabbione** [comment]
closed the wrong issue, reopening

**Comment by digimer** [comment]
Reproduced

**Comment by digimer** [comment]
two problems, one fixed already, the other I am trying to think about how to resolve. Race conditions, of course.

**Comment by digimer** [comment]
Should be fixed by commit 895f1ec in PR#326

**Comment by digimer** [comment]
Should be fixed in main, please re-open if the issue re-appears.

**Comment by fabbione** [comment]
this is not fixed. Executing the above for loops corrupts drbd configuration:

lvs are created correctly:

```
# lvs
  LV                VG            Attr       LSize  Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  an-test-deploy1_0 anvil-test-vg -wi-ao---- 10.00g
  an-test-deploy2_0 anvil-test-vg -wi-ao---- 10.00g
  an-test-deploy3_0 anvil-test-vg -wi-a----- 10.00g
  an-test-deploy4_0 anvil-test-vg -wi-ao---- 10.00g
  an-test-deploy5_0 anvil-test-vg -wi-a----- 10.00g

# drbdadm status
drbd.d/an-test-deploy5.res:0: conflicting use of device-minor 'device-minor:an-a01n01:5' ...
drbd.d/an-test-deploy3.res:0: device-minor 'device-minor:an-a01n01:5' first used here.

  * an-test-deploy1     (ocf::alteeve:server):   Started an-a01n01
  * an-test-deploy2     (ocf::alteeve:server):   Started an-a01n01
  * an-test-deploy4     (ocf::alteeve:server):   Started an-a01n01
```

**Comment by fabbione** [comment]
bumping to urgent at it causes drbd config corruption and drbd unable to operate.

**Comment by fabbione** [comment]
This appears to be fixed with PR#335. While it takes some time to deploy, all servers come up without issues.

**Comment by fabbione** [comment]
Fixed in latest anvil.
