### ISSUE TITLE
incorrect log entry

### ISSUE THREAD

**Issue by fabbione** [ClusterLabs/anvil#338]
2023/06/17 05:28:21:[scan-server]:scan-server:852; The amount of RAM the server: [an-test-deploy3] is currently using has changed from: [4.00 GiB] to: [4 KiB] (from: [4,294,967,296 bytes] to: [4,096 bytes]).
2023/06/17 05:28:21:[scan-server]:scan-server:869; The amount of RAM configured for the server: [an-test-deploy3] has changed from: [4.00 GiB] to: [4 KiB] (from: [4,294,967,296 bytes] to: [4,096 bytes]).

It should be the other way around.. from 4096 bytes to 4,00GiB :P

**Comment by digimer** [comment]
Should be resolved in 9ebe192

**Comment by fabbione** [comment]
This is not fully resolved yet:

[root@an-a01n01 log]# grep "amount of RAM" anvil*
anvil.log:2023/07/25 05:16:15:[scan-server]:scan-server:893; The amount of RAM the server: [an-test-deploy1] is currently using has changed from: [4 KiB] to: [4.00 GiB] (from: [4,096 bytes] to: [4,294,967,296 bytes]).
anvil.log:2023/07/25 05:16:15:[scan-server]:scan-server:910; The amount of RAM configured for the server: [an-test-deploy1] has changed from: [4.00 GiB] to: [4 KiB] (from: [4,294,967,296 bytes] to: [4,096 bytes]).

**Comment by digimer** [comment]
Found a second instance of the same variable substitution issue. Checked for any others and didn't see any. Fixed in 6a7c992

**Comment by fabbione** [comment]
Fixed in main
