### ISSUE TITLE
[upgrade] drop checks around kernel update and reboot nodes if requested.

### ISSUE THREAD

**Issue by fabbione** [ClusterLabs/anvil#378]
striker-update-cluster -vv --log-secure --clear-cache --reboot --yes

as mentioned before, there is more than just a kernel update that requires a reboot, for example kmods updates or new glibc.

If specified on command line, please reboot the node.

**Comment by digimer** [comment]
If you specify '--reboot' and _any_ packages update, it should reboot. Is that not the case?

**Comment by digimer** [comment]
Following up voice chat; Will check for the reboot issue and the kmod issue

**Comment by digimer** [comment]
Should be resolved in 688e850 (pr #376)

**Comment by fabbione** [comment]
not fully fixed.

I am executing the tool from striker01. During the upgrade process striker02 was not rebooted.

**Comment by digimer** [comment]
I think there might be a misunderstanding... Do you want '--reboot' to _always_ reboot, even if there were no packages to update? So far, so long as at least one package updates, the machine will reboot. I was testing by downgrading 'fence-agents' and re-running striker-update-cluster and it was reliably rebooting. If no RPMs updated, it didn't reboot.

**Comment by fabbione** [comment]
oh I see why this test didn´t trigger the striker reboot.. we are updating kmod and it´s not installed on striker. I will have to add some more packages to upgrade to complete the test.

**Comment by fabbione** [comment]
It appears to be ok in #376 with the new CI update repo.
