### ISSUE TITLE
anvil-shutdown-server --server <name> can fail if the server exists in the DB as DELETED

### ISSUE THREAD

**Issue by digimer** [ClusterLabs/anvil#632]
Either ignore DELETEd servers or actually purge from DB when the same name is used twice.

**Comment by digimer** [comment]
Also make sure that a deleted server replaced by a new server with a different UUID also doesn't cause problems.

**Comment by digimer** [comment]
Given that `anvil-shutdown-server` can run without the DB, this was addressed by checking `libvirtd` to see if the requested server is actually running on the host. So the `DELETED` state in the DB is a non-issue now.

**Comment by fabbione** [comment]
Sending back to development. The new changes make it impossible to shut down a server from the other node, even if the DB is available.

```
  * an-test-deploy1     (ocf:alteeve:server):    Started an-a01n01

[root@an-a01n02 ~]# anvil-shutdown-server --server an-test-deploy1
The server: [an-test-deploy1] was not found to be running on this host. Nothing to do, exiting.
```

There is no reason why this shouldn´t work from node2 if DB is up.

**Comment by digimer** [comment]
Should register a job, will be an easy fix when I'm back

**Comment by digimer** [comment]
PR #793 should resolve this.

**Comment by fabbione** [comment]
Back to development, the issue is not fixed.

Steps to reproduce:
1 create server
2 delete server

```
[root@an-a01n02 ~]# anvil-shutdown-server --server an-test-deploy1
The server: [an-test-deploy1] is running on the host: [], creating a job to shut it down on that host.
DBD::Pg::st execute failed: ERROR:  invalid input syntax for type uuid: "NULL"
LINE 19:     job_host_uuid = 'NULL'
                             ^ at /usr/share/perl5/Anvil/Tools/Database.pm line 18348.
DBD::Pg::db do failed: ERROR:  invalid input syntax for type uuid: "NULL"
LINE 20:     'NULL',
             ^ at /usr/share/perl5/Anvil/Tools/Database.pm line 20195.
The job for the peer: [] has been created with the UUID: [7453c211-034c-4a45-94c5-cca2695399ea].
```

**Comment by digimer** [comment]
Should be fixed in 3566536

**Comment by fabbione** [comment]
Manually tested, we will not add specific automation for this bug as it will be used extensively with storage and server management testing.
