### ISSUE TITLE
[storage] anvil-manage-server-storage add machine parsable output for test automation

### ISSUE THREAD

**Issue by fabbione** [ClusterLabs/anvil#656]

**Comment by digimer** [comment]
I've added `--machine` to `anvil-manage-server-storage`. This shows the list of servers if called with nothing else, and shows the server details if called with `--server <foo>`. 

Let me know if you want machine parseable output. Otherwise, this issue will be resolved when cd390fed merges.

**Comment by digimer** [comment]
This is now merged into main. If you need additional output added to the `--machine` switch, please open a new issue with the additional requirements.

**Comment by fabbione** [comment]
--machine option is available. Generated xml is invalid. Bouncing back to devel

`
[root@an-a01n01 ~]# anvil-manage-server-storage --server an-test-deploy1 --machine
<?xml version="1.0" encoding="UTF-8"?>
<server name="an-test-deploy1" uuid="b7fcc7f1-6291-4453-ac4f-c4fe4567a0b1">
        <disk target="vda boot-order="01" drbd-resource="an-test-deploy1" drbd-volume="0" resource-size="32209268736B" lv-size="32212254720B"metadata-size="2985984B" />
        <optical target="sda boot-order="02" iso="/mnt/shared/files/CentOS-Stream-9-latest-x86_64-dvd1.iso"/>
        <optical target="sdb boot-order="03" iso="/mnt/shared/files/deploy1.iso"/>
        <host name="an-a01n01 type="node" uuid="e3f574c9-2c24-4f34-ad0c-76e64b0276c0"/>
                <disk drbd-volume="0 backing-lv="/dev/anvil-test-vg/an-test-deploy1_0" lv-size="32209268736B" sg-name="Storage group 1" sg-uuid="da87456f-20df-4307-b59a-de0ea15b5f80"/>
        </host>
        <host name="an-a01n02 type="node" uuid="45549b6d-b06a-4dd0-ad42-823e92205f4b"/>
                <disk drbd-volume="0 backing-lv="/dev/anvil-test-vg/an-test-deploy1_0" lv-size="32209268736B" sg-name="Storage group 1" sg-uuid="da87456f-20df-4307-b59a-de0ea15b5f80"/>
        </host>
</server>
[root@an-a01n01 ~]# anvil-manage-server-storage --server an-test-deploy1 --machine | xmllint -
-:3: parser error : attributes construct error
        <disk target="vda boot-order="01" drbd-resource="an-test-deploy1" drbd-volume="
                                      ^
-:3: parser error : Couldn't find end of Start Tag disk line 3
        <disk target="vda boot-order="01" drbd-resource="an-test-deploy1" drbd-volume="
                                      ^
-:4: parser error : attributes construct error
        <optical target="sda boot-order="02" iso="/mnt/shared/files/CentOS-Stream-9-lat
                                         ^
-:4: parser error : Couldn't find end of Start Tag optical line 4
        <optical target="sda boot-order="02" iso="/mnt/shared/files/CentOS-Stream-9-lat
                                         ^
-:5: parser error : attributes construct error
        <optical target="sdb boot-order="03" iso="/mnt/shared/files/deploy1.iso"/>
                                         ^
-:5: parser error : Couldn't find end of Start Tag optical line 5
        <optical target="sdb boot-order="03" iso="/mnt/shared/files/deploy1.iso"/>
                                         ^
-:6: parser error : attributes construct error
        <host name="an-a01n01 type="node" uuid="e3f574c9-2c24-4f34-ad0c-76e64b0276c0"/>
                                    ^
-:6: parser error : Couldn't find end of Start Tag host line 6
        <host name="an-a01n01 type="node" uuid="e3f574c9-2c24-4f34-ad0c-76e64b0276c0"/>
                                    ^
-:7: parser error : attributes construct error
                <disk drbd-volume="0 backing-lv="/dev/anvil-test-vg/an-test-deploy1_0" lv-size
                                                 ^
-:7: parser error : Couldn't find end of Start Tag disk line 7
                <disk drbd-volume="0 backing-lv="/dev/anvil-test-vg/an-test-deploy1_0" lv-size
                                                 ^
-:8: parser error : Opening and ending tag mismatch: server line 2 and host
        </host>
               ^
-:9: parser error : Extra content at the end of the document
        <host name="an-a01n02 type="node" uuid="45549b6d-b06a-4dd0-ad42-823e92205f4b"/>
        ^`

**Comment by digimer** [comment]
Should be fixed now.

```
[root@an-a02n01 ~]# anvil-manage-server-storage --machine | xmllint -
<?xml version="1.0" encoding="UTF-8"?>
<anvil>
	<node name="an-anvil-01" uuid="5403fcd5-73de-4c01-8e29-83d35bdf6bf4" description="Demo VM Anvil!">
		<server count="2"/>
		<server name="srv01-win11" uuid="d988af36-d7b3-45fa-899e-0c8a45e94d95"/>
		<server name="srv02-db" uuid="a7413ca0-c496-4e55-b28b-442ecaff7b5a"/>
	</node>
	<node name="an-anvil-02" uuid="dae4f61c-73c4-487c-b508-35d330e111ee" description="Demo RHEL 9 VM Anvil!">
		<server count="0"/>
	</node>
	<node name="an-anvil-03" uuid="33124069-4d04-4696-9530-514b96325921" description="Demo VM Anvil! Node 3">
		<server count="2"/>
		<server name="srv01-test" uuid="b5921871-22c8-4b98-8bad-719ad029f19a"/>
		<server name="srv02-test" uuid="5f231496-a3a1-4b9c-a066-f379e068ae12"/>
	</node>
</anvil>
```

**Comment by fabbione** [comment]
Still broken, sending back to devel:

`
[root@an-a01n01 ~]# anvil-manage-server-storage --machine | xmllint -
-:3: parser error : attributes construct error
de name="an-anvil-01" uuid="e5aa331c-edda-4c40-9910-09480451ea49" description=""
                                                                               ^
-:3: parser error : Couldn't find end of Start Tag node line 3
de name="an-anvil-01" uuid="e5aa331c-edda-4c40-9910-09480451ea49" description=""
                                                                               ^
-:5: parser error : Opening and ending tag mismatch: anvil line 2 and node
        </node>
               ^
-:6: parser error : Extra content at the end of the document
</anvil>
^
[root@an-a01n01 ~]# anvil-manage-server-storage --machine
<?xml version="1.0" encoding="UTF-8"?>
<anvil>
        <node name="an-anvil-01" uuid="e5aa331c-edda-4c40-9910-09480451ea49" description=""Test Anvil! running on gravitar"">
                <server count="0" />
        </node>
</anvil>
[root@an-a01n01 ~]#
`

**Comment by digimer** [comment]
I can't reproduce at the moment. Are you still seeing the issue?

```
[root@an-striker01 ~]# anvil-manage-server-storage --machine | xmllint -
<?xml version="1.0" encoding="UTF-8"?>
<anvil>
	<node name="an-anvil-01" uuid="5403fcd5-73de-4c01-8e29-83d35bdf6bf4" description="Demo VM Anvil!">
		<server count="2"/>
		<server name="srv01-win11" uuid="d988af36-d7b3-45fa-899e-0c8a45e94d95"/>
		<server name="srv02-db" uuid="a7413ca0-c496-4e55-b28b-442ecaff7b5a"/>
	</node>
	<node name="an-anvil-02" uuid="dae4f61c-73c4-487c-b508-35d330e111ee" description="Demo RHEL 9 VM Anvil!">
		<server count="0"/>
	</node>
	<node name="an-anvil-03" uuid="33124069-4d04-4696-9530-514b96325921" description="">
		<server count="2"/>
		<server name="srv01-test" uuid="b5921871-22c8-4b98-8bad-719ad029f19a"/>
		<server name="srv02-test" uuid="5f231496-a3a1-4b9c-a066-f379e068ae12"/>
	</node>
</anvil>
```

**Comment by fabbione** [comment]
Bouncing back to devel:

Generic state is now ok:

```
# anvil-manage-server-storage  --machine | xmllint -
<?xml version="1.0" encoding="UTF-8"?>
<anvil>
        <node name="an-anvil-01" uuid="f4333ecc-adac-40ac-8120-44d94318e52b" description="&quot;Test Anvil! running on gravitar&quot;">
                <server count="1"/>
                <server name="an-test-deploy1" uuid="c3a813d2-916e-4f0f-9d55-4d6ea7f32aa3"/>
        </node>
</anvil>
# # echo $?
0
```

still not working properly for server output.

```
# anvil-manage-server-storage --server an-test-deploy1 --machine|xmllint -
-:3: parser error : attributes construct error
        <disk target="vda boot-order="01" drbd-resource="an-test-deploy1" drbd-volume="
                                      ^
-:3: parser error : Couldn't find end of Start Tag disk line 3
        <disk target="vda boot-order="01" drbd-resource="an-test-deploy1" drbd-volume="
                                      ^
-:4: parser error : attributes construct error
        <optical target="sda boot-order="02" iso="/mnt/shared/files/CentOS-Stream-9-lat
                                         ^
-:4: parser error : Couldn't find end of Start Tag optical line 4
        <optical target="sda boot-order="02" iso="/mnt/shared/files/CentOS-Stream-9-lat
                                         ^
-:5: parser error : attributes construct error
        <optical target="sdb boot-order="03" iso="/mnt/shared/files/deploy1.iso"/>
                                         ^
-:5: parser error : Couldn't find end of Start Tag optical line 5
        <optical target="sdb boot-order="03" iso="/mnt/shared/files/deploy1.iso"/>
                                         ^
-:6: parser error : attributes construct error
        <host name="an-a01n01 type="node" uuid="1c1d3156-d81e-467c-86fc-e02eed4c4a77"/>
                                    ^
-:6: parser error : Couldn't find end of Start Tag host line 6
        <host name="an-a01n01 type="node" uuid="1c1d3156-d81e-467c-86fc-e02eed4c4a77"/>
                                    ^
-:7: parser error : attributes construct error
                <disk drbd-volume="0 backing-lv="/dev/anvil-test-vg/an-test-deploy1_0" lv-size
                                                 ^
-:7: parser error : Couldn't find end of Start Tag disk line 7
                <disk drbd-volume="0 backing-lv="/dev/anvil-test-vg/an-test-deploy1_0" lv-size
                                                 ^
-:8: parser error : Opening and ending tag mismatch: server line 2 and host
        </host>
               ^
-:9: parser error : Extra content at the end of the document
        <host name="an-a01n02 type="node" uuid="97dbfd97-8749-41c5-a5d4-d7caa708a7b3"/>
        ^
```

There are missing " here and there.

**Comment by fabbione** [comment]
Back again, #820 introduces a regression:

```
[root@an-a01n01 ~]# anvil-manage-server-storage  --machine | xmllint -
-:8: parser error : Extra content at the end of the document
Please specify which server you want to modify using '--server <name or uuid>'.
^
[root@an-a01n01 ~]# anvil-manage-server-storage  --machine
<?xml version="1.0" encoding="UTF-8"?>
<anvil>
        <node name="an-anvil-01" uuid="cbf6deae-f815-4e3f-a24a-f11369a6ac4d" description="&quot;Test Anvil! running on gravitar&quot;" >
                <server count="1" />
                <server name="an-test-deploy1" uuid="25e69502-ee02-42c0-b81c-093100558f74" />
        </node>
</anvil>
Please specify which server you want to modify using '--server <name or uuid>'.
```

This used to work, now it spits this last line error that fails to validate xml and return 0.

The server parsing appears to be fixed now.

**Comment by digimer** [comment]
This was caused by `Job->update_progress()` calls set to `print` to STDOUT. Now conditional on `--machine` _not_ being used.

**Comment by fabbione** [comment]
Looks good ok now. Pending automation.
