### ISSUE TITLE
[storage]  anvil-manage-server-storage database gets corrupted in server delete / create

### ISSUE THREAD

**Issue by fabbione** [ClusterLabs/anvil#657]
Reproducer is easy, just takes time:

provision a server:

anvil-provision-server --ci-test --name an-test-deploy1 --os centos-stream9 --cpu 4 --ram 4G --storage-group "Storage group 1" --storage-size 30G --install-media CentOS-Stream-9-latest-x86_64-dvd1.iso --driver-disc deploy1.iso

(wait for server to be deployed)

```
anvil-manage-server-storage -vvv --log-secure --server an-test-deploy1
Working with the server: [an-test-deploy1], UUID: [a89d7fd5-1a1e-4c27-8148-056bd564ddea]

Disk Drives:
- Target: [vda], boot: [01], Replication Volume: [an-test-deploy1/0]
 |- Resource / LV / Metadata sizes: [30.00 GiB / 30.00 GiB / 2.85 MiB], free space: [170.00 GiB]

Optical Drives:
- Target: [sda], boot: [02], ISO: [/mnt/shared/files/CentOS-Stream-9-latest-x86_64-dvd1.iso]
- Target: [sdb], boot: [03], ISO: [/mnt/shared/files/deploy1.iso]

Subnodes:
 |- Name: [an-a01n01], UUID: [94b3bad6-2c4f-499e-b3e8-7cccb06793e5]
   |- Volume: [0], backing device: [/dev/anvil-test-vg/an-test-deploy1_0], DRBD minor: [0], size: [30.00 GiB]
   ^- In storage group: [Storage group 1], size: [200.00 GiB], free: [170.00 GiB]
 |- Name: [an-a01n02], UUID: [14d0bb17-6160-4f59-aa43-5a300653445b]
   |- Volume: [0], backing device: [/dev/anvil-test-vg/an-test-deploy1_0], DRBD minor: [0], size: [30.00 GiB]
   ^- In storage group: [Storage group 1], size: [200.00 GiB], free: [170.00 GiB]
```

Add a disk:

anvil-manage-server-storage -vvv --log-secure --add 20G --disk vdb --server an-test-deploy1 --storage-group "Storage group 1" --confirm

disk is visible in the VM:

ssh an-test-deploy1 cat /proc/partitions |grep vdb
 252       16   20969564 vdb

```
 anvil-manage-server-storage -vvv --log-secure --server an-test-deploy1
Working with the server: [an-test-deploy1], UUID: [a89d7fd5-1a1e-4c27-8148-056bd564ddea]

Disk Drives:
- Target: [vda], boot: [01], Replication Volume: [an-test-deploy1/0]
 |- Resource / LV / Metadata sizes: [30.00 GiB / 30.00 GiB / 2.85 MiB], free space: [170.00 GiB]
Use of uninitialized value $drbd_volume in hash element at /usr/sbin/anvil-manage-server-storage line 2938.
Use of uninitialized value $lv_name in hash element at /usr/sbin/anvil-manage-server-storage line 2940.
Use of uninitialized value $resource_size in subtraction (-) at /usr/sbin/anvil-manage-server-storage line 2941.
Use of uninitialized value $lv_size in subtraction (-) at /usr/sbin/anvil-manage-server-storage line 2941.
Use of uninitialized value $drbd_volume in hash element at /usr/sbin/anvil-manage-server-storage line 3098.
Use of uninitialized value $drbd_volume in hash element at /usr/sbin/anvil-manage-server-storage line 3099.
Use of uninitialized value $drbd_volume in hash element at /usr/sbin/anvil-manage-server-storage line 3100.
Use of uninitialized value $backing_lv in hash element at /usr/sbin/anvil-manage-server-storage line 3101.
Use of uninitialized value $drbd_volume in hash element at /usr/sbin/anvil-manage-server-storage line 3098.
Use of uninitialized value $drbd_volume in hash element at /usr/sbin/anvil-manage-server-storage line 3099.
Use of uninitialized value $drbd_volume in hash element at /usr/sbin/anvil-manage-server-storage line 3100.
Use of uninitialized value $backing_lv in hash element at /usr/sbin/anvil-manage-server-storage line 3101.
- Target: [vdb], boot: [--], Replication Volume: [an-test-deploy1/]
 |- Resource / LV / Metadata sizes: [0 B / 0 B / 0 B], free space: [0 B]

Optical Drives:
- Target: [sda], boot: [02], ISO: [/mnt/shared/files/CentOS-Stream-9-latest-x86_64-dvd1.iso]
- Target: [sdb], boot: [03], ISO: [/mnt/shared/files/deploy1.iso]

Subnodes:
 |- Name: [an-a01n01], UUID: [94b3bad6-2c4f-499e-b3e8-7cccb06793e5]
   |- Volume: [0], backing device: [/dev/anvil-test-vg/an-test-deploy1_0], DRBD minor: [0], size: [30.00 GiB]
   ^- In storage group: [Storage group 1], size: [200.00 GiB], free: [170.00 GiB]
Use of uninitialized value $this_scan_lvm_lv_path in string eq at /usr/sbin/anvil-manage-server-storage line 3265.
   |- Volume: [1], backing device: [/dev/anvil-test-vg/an-test-deploy1_1], DRBD minor: [1], size: [20.00 GiB]
   ^- In storage group: [<unknown>], size: [0 B], free: [0 B]
Use of uninitialized value $this_scan_lvm_lv_path in string eq at /usr/sbin/anvil-manage-server-storage line 3265.
 |- Name: [an-a01n02], UUID: [14d0bb17-6160-4f59-aa43-5a300653445b]
   |- Volume: [0], backing device: [/dev/anvil-test-vg/an-test-deploy1_0], DRBD minor: [0], size: [30.00 GiB]
   ^- In storage group: [Storage group 1], size: [200.00 GiB], free: [170.00 GiB]
Use of uninitialized value $this_scan_lvm_lv_path in string eq at /usr/sbin/anvil-manage-server-storage line 3265.
   |- Volume: [1], backing device: [/dev/anvil-test-vg/an-test-deploy1_1], DRBD minor: [1], size: [20.00 GiB]
   ^- In storage group: [<unknown>], size: [0 B], free: [0 B]
Use of uninitialized value $this_scan_lvm_lv_path in string eq at /usr/sbin/anvil-manage-server-storage line 3265.
```

after some minutes, the output goes back to normal:

```
anvil-manage-server-storage -vvv --log-secure --server an-test-deploy1
Working with the server: [an-test-deploy1], UUID: [a89d7fd5-1a1e-4c27-8148-056bd564ddea]

Disk Drives:
- Target: [vda], boot: [01], Replication Volume: [an-test-deploy1/0]
 |- Resource / LV / Metadata sizes: [30.00 GiB / 30.00 GiB / 2.85 MiB], free space: [150.00 GiB]
- Target: [vdb], boot: [--], Replication Volume: [an-test-deploy1/1]
 |- Resource / LV / Metadata sizes: [20.00 GiB / 20.00 GiB / 1.91 MiB], free space: [150.00 GiB]

Optical Drives:
- Target: [sda], boot: [02], ISO: [/mnt/shared/files/CentOS-Stream-9-latest-x86_64-dvd1.iso]
- Target: [sdb], boot: [03], ISO: [/mnt/shared/files/deploy1.iso]

Subnodes:
 |- Name: [an-a01n01], UUID: [94b3bad6-2c4f-499e-b3e8-7cccb06793e5]
   |- Volume: [0], backing device: [/dev/anvil-test-vg/an-test-deploy1_0], DRBD minor: [0], size: [30.00 GiB]
   ^- In storage group: [Storage group 1], size: [200.00 GiB], free: [150.00 GiB]
   |- Volume: [1], backing device: [/dev/anvil-test-vg/an-test-deploy1_1], DRBD minor: [1], size: [20.00 GiB]
   ^- In storage group: [Storage group 1], size: [200.00 GiB], free: [150.00 GiB]
 |- Name: [an-a01n02], UUID: [14d0bb17-6160-4f59-aa43-5a300653445b]
   |- Volume: [0], backing device: [/dev/anvil-test-vg/an-test-deploy1_0], DRBD minor: [0], size: [30.00 GiB]
   ^- In storage group: [Storage group 1], size: [200.00 GiB], free: [150.00 GiB]
   |- Volume: [1], backing device: [/dev/anvil-test-vg/an-test-deploy1_1], DRBD minor: [1], size: [20.00 GiB]
   ^- In storage group: [Storage group 1], size: [200.00 GiB], free: [150.00 GiB]
```

delete the server:

anvil-delete-server -vv --log-secure --force --server an-test-deploy1

make sure all server resources have been released:
pcs status |grep deploy1
drbdadm status
# No currently configured DRBD found.
lvs

no mention of deploy1.

recreate the server:

anvil-provision-server --ci-test --name an-test-deploy1 --os centos-stream9 --cpu 4 --ram 4G --storage-group "Storage group 1" --storage-size 30G --install-media CentOS-Stream-9-latest-x86_64-dvd1.iso --driver-disc deploy1.iso

```
[root@an-a01n01 ~]# pcs status |grep deploy1
  * an-test-deploy1     (ocf:alteeve:server):    Started an-a01n01
[root@an-a01n01 ~]# anvil-manage-server-storage -vvv --log-secure --server an-test-deploy1
Working with the server: [an-test-deploy1], UUID: [a89d7fd5-1a1e-4c27-8148-056bd564ddea]
The server: [an-test-deploy1] has been deleted.
```

wait some time and observe the DB corruption. The VM, that is brand new and created with only one disk, still expects an extra disk that does not exist:

```
 anvil-manage-server-storage -vvv --log-secure --server an-test-deploy1
Working with the server: [an-test-deploy1], UUID: [a89d7fd5-1a1e-4c27-8148-056bd564ddea]
The server: [an-test-deploy1] has been deleted.
[root@an-a01n01 ~]# anvil-manage-server-storage -vvv --log-secure --server an-test-deploy1
Working with the server: [an-test-deploy1], UUID: [84874f9a-8100-4a2f-b1d7-29a5972ecb2f]

Disk Drives:
- Target: [vda], boot: [01], Replication Volume: [an-test-deploy1/0]
 |- Resource / LV / Metadata sizes: [30.00 GiB / 30.00 GiB / 2.85 MiB], free space: [170.00 GiB]

Optical Drives:
- Target: [sda], boot: [02], ISO: [/mnt/shared/files/CentOS-Stream-9-latest-x86_64-dvd1.iso]
- Target: [sdb], boot: [03], ISO: [/mnt/shared/files/deploy1.iso]

Subnodes:
 |- Name: [an-a01n01], UUID: [94b3bad6-2c4f-499e-b3e8-7cccb06793e5]
   |- Volume: [0], backing device: [/dev/anvil-test-vg/an-test-deploy1_0], DRBD minor: [0], size: [30.00 GiB]
   ^- In storage group: [Storage group 1], size: [200.00 GiB], free: [170.00 GiB]
   |- Volume: [1], backing device: [], DRBD minor: [1], size: [20.00 GiB]
   ^- In storage group: [<unknown>], size: [0 B], free: [0 B]
Use of uninitialized value $backing_disk in string eq at /usr/sbin/anvil-manage-server-storage line 3265.
Use of uninitialized value $backing_disk in string eq at /usr/sbin/anvil-manage-server-storage line 3265.
 |- Name: [an-a01n02], UUID: [14d0bb17-6160-4f59-aa43-5a300653445b]
   |- Volume: [0], backing device: [/dev/anvil-test-vg/an-test-deploy1_0], DRBD minor: [0], size: [30.00 GiB]
   ^- In storage group: [Storage group 1], size: [200.00 GiB], free: [170.00 GiB]
   |- Volume: [1], backing device: [], DRBD minor: [1], size: [20.00 GiB]
   ^- In storage group: [<unknown>], size: [0 B], free: [0 B]
Use of uninitialized value $backing_disk in string eq at /usr/sbin/anvil-manage-server-storage line 3265.
Use of uninitialized value $backing_disk in string eq at /usr/sbin/anvil-manage-server-storage line 3265.
```

**Comment by digimer** [comment]
I tried to reproduce this and the issue did not reappear. I tested on a dev system, not in CI, so it's possible it remains. Can this test be re-enabled to see if the issue remains?

Also, please use `-vv`. Using `-vvv` is discouraged unless debugging issues where the source of a problem is unknown, as `-vvv` generates absolutely massive amounts of logging.

**Comment by digimer** [comment]
I'm closing this as it should be fixed now. If the issue reappears, reopen this issue.

**Comment by fabbione** [comment]
Not fixed yet..

create server
add disk or something
delete server
create server with the same name:

```
# anvil-manage-server-storage --server an-test-deploy1
Working with the server: [an-test-deploy1], UUID: [fafb73dd-b869-439e-9134-7cc0ad8ec4d0]

Disk Drives:
- Target: [vda], boot: [01], Replication Volume: [an-test-deploy1/0]
 |- Resource / LV / Metadata sizes: [30.00 GiB / 30.00 GiB / 2.85 MiB], free space: [170.00 GiB]

Optical Drives:
- Target: [sda], boot: [02], ISO: [/mnt/shared/files/CentOS-Stream-9-latest-x86_64-dvd1.iso]
- Target: [sdb], boot: [03], ISO: [/mnt/shared/files/deploy1.iso]

Subnodes:
 |- Name: [an-a01n01], UUID: [d3caa20a-d051-4238-ad1d-2f09d15c1601]
   |- Volume: [0], backing device: [/dev/anvil-test-vg/an-test-deploy1_0], DRBD minor: [0], size: [30.00 GiB]
   ^- In storage group: [Storage group 1], size: [200.00 GiB], free: [170.00 GiB]
   |- Volume: [1], backing device: [], DRBD minor: [1], size: [20.00 GiB]
   ^- In storage group: [<unknown>], size: [0 B], free: [0 B]
Use of uninitialized value $backing_disk in string eq at /usr/sbin/anvil-manage-server-storage line 3585.
Use of uninitialized value $backing_disk in string eq at /usr/sbin/anvil-manage-server-storage line 3585.
Use of uninitialized value $backing_disk in string eq at /usr/sbin/anvil-manage-server-storage line 3585.
Use of uninitialized value $backing_disk in string eq at /usr/sbin/anvil-manage-server-storage line 3585.
   |- Volume: [2], backing device: [], DRBD minor: [2], size: [10.00 GiB]
   ^- In storage group: [<unknown>], size: [0 B], free: [0 B]
Use of uninitialized value $backing_disk in string eq at /usr/sbin/anvil-manage-server-storage line 3585.
Use of uninitialized value $backing_disk in string eq at /usr/sbin/anvil-manage-server-storage line 3585.
Use of uninitialized value $backing_disk in string eq at /usr/sbin/anvil-manage-server-storage line 3585.
Use of uninitialized value $backing_disk in string eq at /usr/sbin/anvil-manage-server-storage line 3585.
 |- Name: [an-a01n02], UUID: [b635553f-0b44-4613-ba61-c7fae5bfe4f9]
   |- Volume: [0], backing device: [/dev/anvil-test-vg/an-test-deploy1_0], DRBD minor: [0], size: [30.00 GiB]
   ^- In storage group: [Storage group 1], size: [200.00 GiB], free: [170.00 GiB]
   |- Volume: [1], backing device: [], DRBD minor: [1], size: [20.00 GiB]
   ^- In storage group: [<unknown>], size: [0 B], free: [0 B]
Use of uninitialized value $backing_disk in string eq at /usr/sbin/anvil-manage-server-storage line 3585.
Use of uninitialized value $backing_disk in string eq at /usr/sbin/anvil-manage-server-storage line 3585.
Use of uninitialized value $backing_disk in string eq at /usr/sbin/anvil-manage-server-storage line 3585.
Use of uninitialized value $backing_disk in string eq at /usr/sbin/anvil-manage-server-storage line 3585.
   |- Volume: [2], backing device: [], DRBD minor: [2], size: [10.00 GiB]
   ^- In storage group: [<unknown>], size: [0 B], free: [0 B]
Use of uninitialized value $backing_disk in string eq at /usr/sbin/anvil-manage-server-storage line 3585.
Use of uninitialized value $backing_disk in string eq at /usr/sbin/anvil-manage-server-storage line 3585.
Use of uninitialized value $backing_disk in string eq at /usr/sbin/anvil-manage-server-storage line 3585.
Use of uninitialized value $backing_disk in string eq at /usr/sbin/anvil-manage-server-storage line 3585.
Done!
```

**Comment by digimer** [comment]
Should now be fixed in PR #820

**Comment by fabbione** [comment]
Something is off with this fix or some unrelated changes are causing issue:

```
create the server
delete the server
re-create the server
start polling:

[root@an-a01n01 ~]# anvil-manage-server-storage --server an-test-deploy1
Working with the server: [an-test-deploy1], UUID: [25e69502-ee02-42c0-b81c-093100558f74]
The server: [an-test-deploy1] has been deleted.

^^ repeat this a few times, expected, waiting for DB to be updated.

[root@an-a01n01 ~]# anvil-manage-server-storage --server an-test-deploy1
Working with the server: [an-test-deploy1], UUID: [a803707e-aae2-4d69-aa20-9bdefdb7bffc]

Disk Drives:
- Target: [vda], boot: [01], Replication Volume: [an-test-deploy1/0]
 |- Resource / LV / Metadata sizes: [30.00 GiB / 30.00 GiB / 2.85 MiB], free space: [170.00 GiB]

Optical Drives:
- Target: [sda], boot: [02], ISO: [/mnt/shared/files/CentOS-Stream-9-latest-x86_64-dvd1.iso]
- Target: [sdb], boot: [03], ISO: [/mnt/shared/files/deploy1.iso]

Subnodes:
 |- Name: [an-a01n01], UUID: [b5000899-db07-411c-bede-1d9f20bae651]
   |- Volume: [0], backing device: [/dev/anvil-test-vg/an-test-deploy1_0], DRBD minor: [0], size: [30.00 GiB]
   ^- In storage group: [Storage group 1], size: [200.00 GiB], free: [170.00 GiB]
 |- Name: [an-a01n02], UUID: [6cd7ea0b-f3ce-452d-ada6-c5a64344d8e1]
   |- Volume: [0], backing device: [/dev/anvil-test-vg/an-test-deploy1_0], DRBD minor: [0], size: [30.00 GiB]
   ^- In storage group: [Storage group 1], size: [200.00 GiB], free: [170.00 GiB]
Done!

^^^^ at this point the resource-agent did timeout monitoring the VM and trying to shut it down:

  * an-test-deploy1     (ocf:alteeve:server):    Stopping an-a01n01 (disabled)

```

I also noticed, and it might be related, that anvil-delete-server cause the server to first go in FAILED mode, then later deleted.

If it is a different issue, then please open a new bug. This is theoretically fixed.

**Comment by fabbione** [comment]
The issue is theoretically fixed, but there is a potential race condition between:

* add a disk
* output is correct

```

[root@an-a01n01 ~]#   anvil-manage-server-storage -vvv --log-secure --add 20G --disk vdb --server an-test-deploy1 --storage-group "Storage group 1" --confirm
Working with the server: [an-test-deploy1], UUID: [a803707e-aae2-4d69-aa20-9bdefdb7bffc]

start polling for status:

[root@an-a01n01 ~]# anvil-manage-server-storage --server an-test-deploy1
Working with the server: [an-test-deploy1], UUID: [a803707e-aae2-4d69-aa20-9bdefdb7bffc]

Disk Drives:
- Target: [vda], boot: [01], Replication Volume: [an-test-deploy1/0]
 |- Resource / LV / Metadata sizes: [30.00 GiB / 30.00 GiB / 2.85 MiB], free space: [150.00 GiB]
Use of uninitialized value $drbd_volume in hash element at /usr/sbin/anvil-manage-server-storage line 3446.
Use of uninitialized value $lv_name in hash element at /usr/sbin/anvil-manage-server-storage line 3448.
Use of uninitialized value $resource_size in subtraction (-) at /usr/sbin/anvil-manage-server-storage line 3449.
Use of uninitialized value $lv_size in subtraction (-) at /usr/sbin/anvil-manage-server-storage line 3449.
Use of uninitialized value $drbd_volume in hash element at /usr/sbin/anvil-manage-server-storage line 3724.
Use of uninitialized value $drbd_volume in hash element at /usr/sbin/anvil-manage-server-storage line 3725.
Use of uninitialized value $drbd_volume in hash element at /usr/sbin/anvil-manage-server-storage line 3726.
Use of uninitialized value $backing_lv in hash element at /usr/sbin/anvil-manage-server-storage line 3727.
Use of uninitialized value $drbd_volume in hash element at /usr/sbin/anvil-manage-server-storage line 3724.
Use of uninitialized value $drbd_volume in hash element at /usr/sbin/anvil-manage-server-storage line 3725.
Use of uninitialized value $drbd_volume in hash element at /usr/sbin/anvil-manage-server-storage line 3726.
Use of uninitialized value $backing_lv in hash element at /usr/sbin/anvil-manage-server-storage line 3727.
- Target: [vdb], boot: [--], Replication Volume: [an-test-deploy1/]
 |- Resource / LV / Metadata sizes: [0 B / 0 B / 0 B], free space: [0 B]

Optical Drives:
- Target: [sda], boot: [02], ISO: [/mnt/shared/files/CentOS-Stream-9-latest-x86_64-dvd1.iso]
- Target: [sdb], boot: [03], ISO: [/mnt/shared/files/deploy1.iso]

Subnodes:
 |- Name: [an-a01n01], UUID: [b5000899-db07-411c-bede-1d9f20bae651]
   |- Volume: [0], backing device: [/dev/anvil-test-vg/an-test-deploy1_0], DRBD minor: [0], size: [30.00 GiB]
   ^- In storage group: [Storage group 1], size: [200.00 GiB], free: [150.00 GiB]
Use of uninitialized value $this_scan_lvm_lv_path in string eq at /usr/sbin/anvil-manage-server-storage line 3931.
 |- Name: [an-a01n02], UUID: [6cd7ea0b-f3ce-452d-ada6-c5a64344d8e1]
   |- Volume: [0], backing device: [/dev/anvil-test-vg/an-test-deploy1_0], DRBD minor: [0], size: [30.00 GiB]
   ^- In storage group: [Storage group 1], size: [200.00 GiB], free: [150.00 GiB]
Use of uninitialized value $this_scan_lvm_lv_path in string eq at /usr/sbin/anvil-manage-server-storage line 3931.
   |- Volume: [1], backing device: [], DRBD minor: [1], size: [0 B]
   ^- In storage group: [<unknown>], size: [0 B], free: [0 B]
Use of uninitialized value $backing_disk in string eq at /usr/sbin/anvil-manage-server-storage line 3931.
Use of uninitialized value $this_scan_lvm_lv_path in string eq at /usr/sbin/anvil-manage-server-storage line 3931.
Use of uninitialized value $this_scan_lvm_lv_on_vg in exists at /usr/sbin/anvil-manage-server-storage line 3938.
Use of uninitialized value $this_scan_lvm_lv_on_vg in hash element at /usr/sbin/anvil-manage-server-storage line 3940.
Use of uninitialized value $this_scan_lvm_lv_on_vg in hash element at /usr/sbin/anvil-manage-server-storage line 3941.
Use of uninitialized value $backing_disk in string eq at /usr/sbin/anvil-manage-server-storage line 3931.
Use of uninitialized value $backing_disk in string eq at /usr/sbin/anvil-manage-server-storage line 3931.
Done!

at some point it will be ok:

[root@an-a01n01 ~]# anvil-manage-server-storage --server an-test-deploy1
Working with the server: [an-test-deploy1], UUID: [a803707e-aae2-4d69-aa20-9bdefdb7bffc]

Disk Drives:
- Target: [vda], boot: [01], Replication Volume: [an-test-deploy1/0]
 |- Resource / LV / Metadata sizes: [30.00 GiB / 30.00 GiB / 2.85 MiB], free space: [150.00 GiB]
- Target: [vdb], boot: [--], Replication Volume: [an-test-deploy1/1]
 |- Resource / LV / Metadata sizes: [20.00 GiB / 20.00 GiB / 1.91 MiB], free space: [150.00 GiB]

Optical Drives:
- Target: [sda], boot: [02], ISO: [/mnt/shared/files/CentOS-Stream-9-latest-x86_64-dvd1.iso]
- Target: [sdb], boot: [03], ISO: [/mnt/shared/files/deploy1.iso]

Subnodes:
 |- Name: [an-a01n01], UUID: [b5000899-db07-411c-bede-1d9f20bae651]
   |- Volume: [0], backing device: [/dev/anvil-test-vg/an-test-deploy1_0], DRBD minor: [0], size: [30.00 GiB]
   ^- In storage group: [Storage group 1], size: [200.00 GiB], free: [150.00 GiB]
   |- Volume: [1], backing device: [/dev/anvil-test-vg/an-test-deploy1_1], DRBD minor: [1], size: [20.00 GiB]
   ^- In storage group: [Storage group 1], size: [200.00 GiB], free: [150.00 GiB]
 |- Name: [an-a01n02], UUID: [6cd7ea0b-f3ce-452d-ada6-c5a64344d8e1]
   |- Volume: [0], backing device: [/dev/anvil-test-vg/an-test-deploy1_0], DRBD minor: [0], size: [30.00 GiB]
   ^- In storage group: [Storage group 1], size: [200.00 GiB], free: [150.00 GiB]
   |- Volume: [1], backing device: [/dev/anvil-test-vg/an-test-deploy1_1], DRBD minor: [1], size: [20.00 GiB]
   ^- In storage group: [Storage group 1], size: [200.00 GiB], free: [150.00 GiB]
Done!

```

I am leaving this open in case the UI uses this output as it can cause issues.

**Comment by digimer** [comment]
So it clears up once the job to add the disk is complete? 

@ylei-tsubame I don't believe you use the output from this call in the UI, right? You use the DB data as the UI's source of truth?

**Comment by digimer** [comment]
Added checks to not try to display incomplete data, so these warnings should no longer be displayed.

**Comment by fabbione** [comment]
looks good now, pending test automation.
